version: '3.8'

services:

  postgres:
    image: postgis/postgis:13-3.1-alpine
    command: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
      - .docker/init/postgres/init_db:/docker-entrypoint-initdb.d


# docker cp backup/dump-cms-202203120554.sql challenge-postgres-1:/tmp/
# docker exec -it challenge-postgres-1 /bin/bash 
# psql -U postgres -d cms < /tmp/dump-cms-202203120554.sql
# exit